export const hololive = [
  {
    name: 'AZKi',
    ytId: 'UC0TXe_LYZ4scaW2XMyi5_kw',
    chName: 'AZKi Channel',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnh85tQLdg3chip7aFBjFZyORHi40WPjcFRWaQq8Wg=s800-c-k-c0x00ffffff-no-rj',
    groups: ['0th Generation', 'Hololive'],
    twitter: 'AZKi_VDiVA',
    aliases: ['azki'],
  },
  {
    name: 'Akai Haato',
    ytId: 'UC1CfXB_kRs3C-zaeTG3oGyg',
    chName: 'HAACHAMA Ch 赤井はあと',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwniwFyaWXOPJEGqA3afhSvRsiPDb0sYt8TlCMMWIig=s800-c-k-c0x00ffffff-no-rj',
    groups: ['1st Generation', 'Hololive'],
    twitter: 'akaihaato',
    aliases: ['haato', 'haachama', 'はあちゃま', 'はあと'],
  },
  {
    name: 'Darkweb Haachama',
    ytId: 'UCHj_mh57PVMXhAUDphUQDFA',
    chName: 'HAACHAMA DARKWEB CH',
    picture: 'n/a',
    groups: ['1st Generation', 'Hololive'],
    twitter: 'akaihaato',
    aliases: [],
  },
  {
    name: 'Usada Pekora',
    ytId: 'UC1DCedRgGHBdm81E1llLhOQ',
    chName: 'Pekora Ch. 兎田ぺこら',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnjvkyPGzOmEXZ34mEFPlwMKTbCDl1ZkQ_HkxY-O5Q=s800-c-k-c0x00ffffff-no-rj',
    groups: ['3rd Generation', 'Hololive'],
    twitter: 'usadapekora',
    aliases: ['peko', 'ペコ', 'ぺこ'],
  },
  {
    name: 'Minato Aqua',
    ytId: 'UC1opHUrw8rvnsadT-iGp7Cg',
    chName: 'Aqua Ch. 湊あくあ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwngPGs1t6iJAT6hLWj7cBQcvJg2y_L9mzpy3lpxgqw=s800-c-k-c0x00ffffff-no-rj',
    groups: ['2nd Generation', 'Hololive'],
    twitter: 'minatoaqua',
    aliases: ['aqua', 'baqua', 'akutan', 'あくあ', 'あくたん'],
  },
  {
    name: 'Yuzuki Choco',
    ytId: 'UC1suqwovbL1kzsoaZgFZLKg',
    chName: 'Choco Ch. 癒月ちょこ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnjONtr2IgqiXteDRhXt_yOiWlgPLicWOESGvKzZPQ=s800-c-k-c0x00ffffff-no-rj',
    groups: ['2nd Generation', 'Hololive'],
    twitter: 'yuzukichococh',
    aliases: ['choco', 'chocosen', 'ちょこ'],
  },
  {
    name: 'Tokoyami Towa',
    ytId: 'UC1uv2Oq6kNxgATlCiez59hw',
    chName: 'Towa Ch. 常闇トワ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnjPaiimZva5GECAyNDn0qraqPm62LlH-0oN21I5=s800-c-k-c0x00ffffff-no-rj',
    groups: ['4th Generation', 'Hololive'],
    twitter: 'tokoyamitowa',
    aliases: ['towa', 'トワ'],
  },
  {
    name: 'Hoshimachi Suisei',
    ytId: 'UC5CwaMl1eIgY8h02uZw7u8A',
    chName: 'Suisei Channel',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnjdAl5rn3IjWzl55_0-skvKced7znPZRuPC5xLB=s800-c-k-c0x00ffffff-no-rj',
    groups: ['0th Generation', 'Hololive'],
    twitter: 'suisei_hosimati',
    aliases: ['suisei', 'suichan', 'sui-chan', 'すいせい', 'すいちゃん'],
  },
  {
    name: 'Hanasaki Miyabi',
    ytId: 'UC6t3-_N8A6ME1JShZHHqOMw',
    chName: 'Miyabi Ch. 花咲みやび',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnj2P4FOShzQPX2-1rLfO_3Vbo7IyKQdK1PiF65w=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Holostars 1st Gen', 'Hololive'],
    twitter: 'miyabihanasaki',
    aliases: ['miyabi', 'みやび'],
  },
  {
    name: 'Anya Melfissa',
    ytId: 'UC727SQYUvx5pDDGQpTICNWg',
    chName: 'Anya Melfissa Ch. hololive-ID',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnie9uw8oBbjgTKmoLPSo9b_K0AbNPRbD2rjCApl=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Indonesia 2nd Gen', 'Hololive'],
    twitter: 'anyamelfissa',
    aliases: ['anya', 'アーニャ'],
  },
  {
    name: 'Nakiri Ayame',
    ytId: 'UC7fk0CB07ly8oSl0aqKkqFg',
    chName: 'Nakiri Ayame Ch. 百鬼あやめ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnh66ZORNcVma4Pn-Qic23kU3Kl4ZkHM3asCWjDh=s800-c-k-c0x00ffffff-no-rj',
    groups: ['2nd Generation', 'Hololive'],
    twitter: 'nakiriayame',
    aliases: ['ayame', 'nakiri', 'あやめ'],
  },
  {
    name: 'Rikkaroid',
    ytId: 'UC9mf_ZVpouoILRY9NUIaK-w',
    chName: 'Rikka ch.律可',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnghUH22DLP22EHC3PZP7xXzJFd7qS_scK95WhaQ=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Holostars 1st Gen', 'Hololive'],
    twitter: 'rikkaroid',
    aliases: ['rikka', 'rikka', 'りっか', '律可'],
  },
  {
    name: 'Himemori Luna',
    ytId: 'UCa9Y57gfeY0Zro_noHRVrnw',
    chName: 'Luna Ch. 姫森ルーナ',
    picture:
      'https://yt3.ggpht.com/eUvyn2QlPppt7z5wew0upiGt2-o7c7rLKBlWynTrSdacjvtZYxZ7Sp6MuYumQJ-zSwzj6a6BDA=s800-c-k-c0x00ffffff-no-rj',
    groups: ['4th Generation', 'Hololive'],
    twitter: 'himemoriluna',
    aliases: ['ルーナ', 'luna'],
  },
  {
    name: 'Yukoku Roberu',
    ytId: 'UCANDOlYTJT7N5jlRC3zfzVA',
    chName: 'Roberu Ch. 夕刻ロベル',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwngPbWJ4YAEgQiAMkgMwLh_0AV_I7SbRhW-s4h_p=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Holostars 2nd Generation', 'Hololive'],
    twitter: 'yukokuroberu',
    aliases: ['winning son', 'roberu', 'ロベル'],
  },
  {
    name: 'Airani Iofifteen',
    ytId: 'UCAoy6rzhSf4ydcYjJw3WoVg',
    chName: 'Airani Iofifteen Channel hololive-ID',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnh4NDjjjUAfPj8Aa4kjyQb4C85KzMWobSCaso-8=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Indonesia 1st Gen', 'Hololive'],
    twitter: 'airaniiofifteen',
    aliases: ['iofi', 'イオフィ'],
  },
  {
    name: 'Momosuzu Nene',
    ytId: 'UCAWSyEs_Io8MtpY3m-zqILA',
    chName: 'Nene Ch.桃鈴ねね',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnilXc5WPsj69fn_xew6see04Cmj3x1vIkW62boi=s800-c-k-c0x00ffffff-no-rj',
    groups: ['5th Generation', 'Hololive'],
    twitter: 'momosuzunene',
    aliases: ['nene', 'ねね', 'nenechi'],
  },
  {
    name: 'Houshou Marine',
    ytId: 'UCCzUftO8KOVkV4wQG1vkUvg',
    chName: 'Marine Ch. 宝鐘マリン',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnjPuFWs42Vx2yIhK7z1w4L-e1GIpHn_5R1uknbS=s800-c-k-c0x00ffffff-no-rj',
    groups: ['3rd Generation', 'Hololive'],
    twitter: 'houshoumarine',
    aliases: ['marine', '船長', 'senchou', 'sentyo', 'mari-tan', 'maripi'],
  },
  {
    name: 'Yozora Mel',
    ytId: 'UCD8HOxPs4Xvsm8H0ZxXGiBw',
    chName: 'Mel Channel 夜空メルチャンネル',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnj5J44v4_Ua9qGrh_n8IR0Dp-r2yj0Nl0mv4lkR=s800-c-k-c0x00ffffff-no-rj',
    groups: ['1st Generation', 'Hololive'],
    twitter: 'yozoramel',
    aliases: ['mel', 'メル'],
  },
  {
    name: 'Shirakami Fubuki',
    ytId: 'UCdn5BQ06XqgXoAxIhbqw5Rg',
    chName: 'フブキCh。白上フブキ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwniEQsukDZoC-l8zchhRzpraxcH7Fyq9amrj2980Aw=s800-c-k-c0x00ffffff-no-rj',
    groups: ['1st Generation', 'Hololive'],
    twitter: 'shirakamifubuki',
    aliases: ['fubuki', 'fbk', 'フブキ'],
  },
  {
    name: 'Roboco-san',
    ytId: 'UCDqI2jOz0weumE8s7paEk6g',
    chName: 'Roboco Ch. - ロボ子',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnhx_THxk2jgqmEGA-cliO482QCna3lnmCBFvCdtBg=s800-c-k-c0x00ffffff-no-rj',
    groups: ['0th Generation', 'Hololive'],
    twitter: 'robocosan',
    aliases: ['roboco', 'ロボ子'],
  },
  {
    name: 'Shirogane Noel',
    ytId: 'UCdyqAaZDKHXg4Ahi7VENThQ',
    chName: 'Noel Ch. 白銀ノエル',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnijLF2X1YBVQo3rClt7ub29cYM7OzpmRmliaGbw=s800-c-k-c0x00ffffff-no-rj',
    groups: ['3rd Generation', 'Hololive'],
    twitter: 'shiroganenoel',
    aliases: ['noel', 'ノエル', 'danchou', '団長'],
  },
  {
    name: 'Yukihana Lamy',
    ytId: 'UCFKOVgVbGmX65RxO3EtH3iw',
    chName: 'Lamy Ch. 雪花ラミィ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwng8eQJdCX3r4RgCmRGwigXkDp9a2JJSPq-dZcMF=s800-c-k-c0x00ffffff-no-rj',
    groups: ['5th Generation', 'Hololive'],
    twitter: 'yukihanalamy',
    aliases: ['lamy', 'らみ', 'ラミィ'],
  },
  {
    name: 'Aki Rosenthal',
    ytId: 'UCFTLzh12_nrtzqBPsTCqenA',
    chName: 'アキロゼCh。Vtuber/ホロライブ所属',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnhPGqWt_E_8rBXpKUTgHCuyTq0Zz7TXlkRtiIww=s800-c-k-c0x00ffffff-no-rj',
    groups: ['1st Generation', 'Hololive'],
    twitter: 'akirosenthal',
    aliases: ['aki', 'アキ'],
  },
  {
    name: 'Kishido Temma',
    ytId: 'UCGNI4MENvnsymYjKiZwv9eg',
    chName: 'Temma Ch. 岸堂天真',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnjek7CeN83n90k6OaFaezz0vdgXe5RYaxl_nPaX=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Holostars 2nd Generation', 'Hololive'],
    twitter: 'kishidotemma',
    aliases: ['temma', '天真', 'てんま'],
  },
  {
    name: 'Inugami Korone',
    ytId: 'UChAnqc_AY5_I3Px5dig3X1Q',
    chName: 'Korone Ch. 戌神ころね',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnj7QwmJ9YhyKY-9SkOKhKIzTKDMJp0HX2vAdQUVdw=s800-c-k-c0x00ffffff-no-rj',
    groups: ['GAMERS', 'Hololive'],
    twitter: 'inugamikorone',
    aliases: ['korone', 'korosan', 'ころね', 'ころさん'],
  },
  {
    name: 'Pavolia Reine',
    ytId: 'UChgTyjG-pdNvxxhdsXfHQ5Q',
    chName: 'Pavolia Reine Ch. hololive-ID',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnjXvzYgBg5mJv8RZLZhgn0-Zb_4zzE1zhCHrJ2w=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Indonesia 2nd Gen', 'Hololive'],
    twitter: 'pavoliareine',
    aliases: ['reine', 'レイネ'],
  },
  {
    name: 'Sakura Miko',
    ytId: 'UC-hM6YJuNYVAmUWxeIr9FeA',
    chName: 'Miko Ch. さくらみこ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwniR0ijvAPNICEVzF8Pz0kSkuhBLKXd31oc5yO-0AQ=s800-c-k-c0x00ffffff-no-rj',
    groups: ['0th Generation', 'Hololive'],
    twitter: 'sakuramiko35',
    aliases: ['miko', 'mikoti', 'mikocchi', 'みこ', 'みこっち'],
  },
  {
    name: 'Kageyama Shien',
    ytId: 'UChSvpZYRPh0FvG4SJGSga3g',
    chName: 'Shien Ch.影山シエン',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnjvoMWzRyWOvk4jbneB4C0O97oCXrLUDV9twwsN=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Holostars 3rd Gen', 'Hololive'],
    twitter: 'kageyamashien',
    aliases: ['shien', 'シエン'],
  },
  {
    name: 'Takanashi Kiara',
    ytId: 'UCHsx4Hqa-1ORjQTh9TYDhww',
    chName: 'Takanashi Kiara Ch. hololive-EN',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnh1s1xECXk9_DaR77i4LBBWkTY-nOi_O0-fPoX8=s800-c-k-c0x00ffffff-no-rj',
    groups: ['English 1st Gen', 'Hololive'],
    twitter: 'takanashikiara',
    aliases: ['kiara', 'tenchou', 'きあら', 'キアラ', '店長'],
  },
  {
    name: 'Takanashi Kiara SubCh',
    ytId: 'UCq4ky2drohLT7W0DmDEw1dQ',
    chName: 'Takanashi Kiara SubCh.',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnh1s1xECXk9_DaR77i4LBBWkTY-nOi_O0-fPoX8=s800-c-k-c0x00ffffff-no-rj',
    groups: ['English 1st Gen', 'Hololive'],
    twitter: 'takanashikiara',
    aliases: [],
  },
  {
    name: 'Omaru Polka',
    ytId: 'UCK9V2B22uJYu3N7eR_BT9QA',
    chName: 'Polka Ch. 尾丸ポルカ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnh-sak3t15svmMDNF8w_uxnNEChOL7C1DKAO-Ht=s800-c-k-c0x00ffffff-no-rj',
    groups: ['5th Generation', 'Hololive'],
    twitter: 'omarupolka',
    aliases: ['polka', 'omaru', 'ポル', 'おまる', 'omarun'],
  },
  {
    name: 'Arurandeisu',
    ytId: 'UCKeAhJvy8zgXWbh9duVjIaQ',
    chName: 'Aruran Ch. アルランディス',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnjIqTphTjcWJLTftb3ppGk71CVwCYaH2M5KkmZOAQ=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Holostars 1st Gen', 'Hololive'],
    twitter: 'arurandeisu',
    aliases: ['aruran'],
  },
  {
    name: 'Mori Calliope',
    ytId: 'UCL_qhgtOy0dy1Agp8vkySQg',
    chName: 'Mori Calliope Ch. hololive-EN',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwniY6zzRc3nUO1zLCBlmaAxeLNDoVWjw0hKGztvJ=s800-c-k-c0x00ffffff-no-rj-mo',
    groups: ['English 1st Gen', 'Hololive'],
    twitter: 'moricalliope',
    aliases: ['calliope', 'calli', 'mori'],
  },
  {
    name: 'Ninomae Ina’nis',
    ytId: 'UCMwGHR0BTZuLsmjY_NT5Pwg',
    chName: "Ninomae Ina'nis Ch. hololive-EN",
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwng37V0l-NwF3bu7QA4XmOP5EZFwk5zJE-78OHP9=s800-c-k-c0x00ffffff-no-rj',
    groups: ['English 1st Gen', 'Hololive'],
    twitter: 'ninomaeinanis',
    aliases: ['ina'],
  },
  {
    name: 'Astel Leda',
    ytId: 'UCNVEsYbiZjH5QLmGeSgTSzg',
    chName: 'astel ch.アステル',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwngMQoYWdT6G-GUOnGKmzbFoLBTdsjb2G5rS8ZbH=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Holostars 2nd Generation'],
    twitter: 'astelleda',
    aliases: ['astel', 'アステル', 'Hololive'],
  },
  {
    name: 'Gawr Gura',
    ytId: 'UCoSrY_IQQVpmIRZ9Xf-y93g',
    chName: 'Gawr Gura Ch. hololive-EN',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnhSSaF3Q-PyyTSis4EH6Cu8FZ32LNvkxI9Gl_rn=s800-c-k-c0x00ffffff-no-rj',
    groups: ['English 1st Gen', 'Hololive'],
    twitter: 'gawrgura',
    aliases: ['gura'],
  },
  {
    name: 'Ayunda Risu',
    ytId: 'UCOyYb1c43VlX9rc_lT6NKQw',
    chName: 'Ayunda Risu Ch. hololive-ID',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwniS_ftaXhqYt1SQPjyuFx5MD_-v0fIUkbCTq5Q_gg=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Indonesia 1st Gen', 'Hololive'],
    twitter: 'ayunda_risu',
    aliases: ['risu', 'ayunda', 'アユンダ'],
  },
  {
    name: 'Moona Hoshinova',
    ytId: 'UCP0BspO_AMEe3aQqqpo89Dg',
    chName: 'Moona Hoshinova hololive-ID',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnj-XzL4TRZCzwo-7FCmdsTikQo9wMZwz9RGNoT0XA=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Indonesia 1st Gen', 'Hololive'],
    twitter: 'moonahoshinova',
    aliases: ['moona', 'ムーナ'],
  },
  {
    name: 'Ookami Mio',
    ytId: 'UCp-5t9SrOQwXMU7iIjQfARg',
    chName: 'Mio Channel 大神ミオ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwng30Wmfu39r1PLrF05pvAafn2a2Ex90ok2C6CTBmg=s800-c-k-c0x00ffffff-no-rj',
    groups: ['GAMERS', 'Hololive'],
    twitter: 'ookamimio',
    aliases: ['mio', 'みお'],
  },
  {
    name: 'Tokino Sora',
    ytId: 'UCp6993wxpyDPHUpavwDFqgg',
    chName: 'SoraCh. ときのそらチャンネル',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwngZmr_qbKhGIvHaHwLRmKhKxdeFfM7ZbK316vFNSw=s800-c-k-c0x00ffffff-no-rj',
    groups: ['0th Generation', 'Hololive'],
    twitter: 'tokino_sora',
    aliases: ['sora', 'そら'],
  },
  {
    name: 'Natsuiro Matsuri',
    ytId: 'UCQ0UDLQCjY0rmuxCDE38FGg',
    chName: 'Matsuri Channel 夏色まつり',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwni8cjtyc08E7rocvO9_gR1b5BhO1O6O1VreDxMW=s800-c-k-c0x00ffffff-no-rj',
    groups: ['1st Generation', 'Hololive'],
    twitter: 'natsuiromatsuri',
    aliases: ['matsuri', 'まつり'],
  },
  {
    name: 'Tsunomaki Watame',
    ytId: 'UCqm3BQLlJfvkTsX_hvm0UmA',
    chName: 'Watame Ch. 角巻わため',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnitWcmmZK60TDG8y5aUeQfZlmH9YlBNJ4D1ZSFI=s800-c-k-c0x00ffffff-no-rj',
    groups: ['4th Generation', 'Hololive'],
    twitter: 'tsunomakiwatame',
    aliases: ['watame', 'わため'],
  },
  {
    name: 'Shishiro Botan',
    ytId: 'UCUKD-uaobj9jiqB-VXt71mA',
    chName: 'Botan Ch.獅白ぼたん',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwngRC-JqguPnj9ljVH3UulyfdlyQzLYzLeSrhvD6=s800-c-k-c0x00ffffff-no-rj',
    groups: ['5th Generation', 'Hololive'],
    twitter: 'shishirobotan',
    aliases: ['botan', 'ぼたん', 'shishiron', 'bossan'],
  },
  {
    name: 'Nekomata Okayu',
    ytId: 'UCvaTdHTWBGv3MKj3KVqJVCw',
    chName: 'Okayu Ch. 猫又おかゆ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnjXQ3Gt3t3SdUMZHBhhEb_c1jqThHfDaVNJF_LJ=s800-c-k-c0x00ffffff-no-rj',
    groups: ['GAMERS', 'Hololive'],
    twitter: 'nekomataokayu',
    aliases: ['okayu', 'おかゆ'],
  },
  {
    name: 'Shiranui Flare',
    ytId: 'UCvInZx9h3jC2JzsIzoOebWg',
    chName: 'Flare Ch. 不知火フレア',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwngtkUgGkgWTz57Er3GSzuMUR07HISM_yDhKQFnR_A=s800-c-k-c0x00ffffff-no-rj',
    groups: ['3rd Generation', 'Hololive'],
    twitter: 'shiranuiflare',
    aliases: ['flare', 'フレア'],
  },
  {
    name: 'Oozora Subaru',
    ytId: 'UCvzGlP9oQwU--Y0r9id_jnA',
    chName: 'Subaru Ch. 大空スバル',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwniCgko15I_x5bYWm0G2vnf5hZqD5hLOtLEDw0Na=s800-c-k-c0x00ffffff-no-rj',
    groups: ['2nd Generation', 'Hololive'],
    twitter: 'oozorasubaru',
    aliases: ['subaru', 'shuba', 'スバル'],
  },
  {
    name: 'Aragami Oga',
    ytId: 'UCwL7dgTxKo8Y4RFIKWaf8gA',
    chName: 'Oga Ch.荒咬オウガ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnie3tYJpu_RdoJWWMjNkj-mUS7-F4QtE1nNY8N_=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Holostars 3rd Gen', 'Hololive'],
    twitter: 'aragamioga',
    aliases: ['oga'],
  },
  {
    name: 'Murasaki Shion',
    ytId: 'UCXTpFs_3PqI41qX2d9tL2Rw',
    chName: 'Shion Ch. 紫咲シオン',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwni5CHNTkw8RlOj-78oqDbWS6sEdH4VQR_c06B6s6Q=s800-c-k-c0x00ffffff-no-rj',
    groups: ['2nd Generation', 'Hololive'],
    twitter: 'murasakishionch',
    aliases: ['shion', 'シオン', 'kusogaki', 'クソガキ'],
  },
  {
    name: 'Watson Amelia',
    ytId: 'UCyl1z3jo3XHR1riLFKG5UAg',
    chName: 'Watson Amelia Ch. hololive-EN',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwngni7uCVYUaj_uiNnA9t1cR1PfIz-rE-GvAVeN_=s800-c-k-c0x00ffffff-no-rj',
    groups: ['English 1st Gen', 'Hololive'],
    twitter: 'watsonameliaen',
    aliases: ['amelia', 'ame'],
  },
  {
    name: 'Kureiji Ollie',
    ytId: 'UCYz_5n-uDuChHtLo7My1HnQ',
    chName: 'Kureiji Ollie Ch. hololive-ID',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnjIfGLTIQT83r0fKch6BBpK0Vuhgwb5_yfCP7Q=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Indonesia 2nd Gen', 'Hololive'],
    twitter: 'kureijiollie',
    aliases: [],
  },
  {
    name: 'Kanade Izuru',
    ytId: 'UCZgOv3YDEs-ZnZWDYVwJdmA',
    chName: 'Izuru Ch. 奏手イヅル',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnhNA5NPSYpFiMba_lmeNqYZJ4bVtZKf-5g5YlxGcA=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Holostars 1st Gen', 'Hololive'],
    twitter: 'kanadeizuru',
    aliases: ['izuru'],
  },
  {
    name: 'Amane Kanata',
    ytId: 'UCZlDXzGoo7d44bwdNObFacg',
    chName: 'Kanata Ch. 天音かなた',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwniXUgLD1FepLsMoqO7HnhlgwbxGmPeqKWGv1JsO=s800-c-k-c0x00ffffff-no-rj',
    groups: ['4th Generation', 'Hololive'],
    twitter: 'amanekanatach',
    aliases: ['kanata', 'かなた', 'pp tenshi', 'かなごり', 'kanataso', 'kanatan', 'kanakana', 'kanata-senpai', 'kanata-san'],
  },
  {
    name: 'IRyS',
    ytId: 'UC8rcEBzJSleTkf_-agPM20g',
    chName: 'IRyS Ch. hololive-EN',
    picture:
      'https://yt3.ggpht.com/UwxlX1PuB_RwJyEUW_ofbBR6saY8n5_p8A9_1bY65zygFrfqIb1GM8dIK33EJboDDnRVyw=s88-c-k-c0x00ffffff-no-rj',
    groups: ['English', 'Hololive'],
    twitter: 'irys_en',
    aliases: ['irys'],
  },
  {
    name: 'Hakos Baelz',
    ytId: 'UCgmPnx-EEeOrZSg5Tiw7ZRQ',
    chName: 'Hakos Baelz Ch. hololive-EN',
    picture:
      'https://yt3.ggpht.com/GWIwRbtVQ2TAlvH8Mf37FMpemTrwmUSbTSazp9Aul6KwdKQmvx7IbLZepDk0sp8ReW3qBhsU=s88-c-k-c0x00ffffff-no-rj',
    groups: ['English 2nd Gen', 'Hololive'],
    twitter: 'hakosbaelz',
    aliases: ['baelz', 'hakos'],
  },
  {
    name: 'Nanashi Mumei',
    ytId: 'UC3n5uGu18FoCy23ggWWp8tA',
    chName: 'Nanashi Mumei Ch. hololive-EN',
    picture:
      'https://yt3.ggpht.com/MI8E8Wfmc_ngNZXUwu8ad0D-OtqDhmqGVULEu25z-ccscwzJpAw-7ewFXzZYLK2jHB9d5OgQDq4=s88-c-k-c0x00ffffff-no-rj',
    groups: ['English 2nd Gen', 'Hololive'],
    twitter: 'nanashimumei_en',
    aliases: ['nanashi', 'mumei'],
  },
  {
    name: 'Ouro Kronii',
    ytId: 'UCmbs8T6MWqUHP1tIQvSgKrg',
    chName: 'Ouro Kronii Ch. hololive-EN',
    picture:
      'https://yt3.ggpht.com/6670YE31bbAtAi7m_UL-KWZBdL5wvmfHlLtcS4HxsBZBQNqmAk7Y-iiIOjawO_0HYXpS4HfC=s88-c-k-c0x00ffffff-no-rj',
    groups: ['English 2nd Gen', 'Hololive'],
    twitter: 'ourokronii',
    aliases: ['kronii'],
  },
  {
    name: 'Ceres Fauna',
    ytId: 'UCO_aKKYxn4tvrqPjcTzZ6EQ',
    chName: 'Ceres Fauna Ch. hololive-EN',
    picture:
      'https://yt3.googleusercontent.com/cBtserkb211p6If2OewgWd8oriIKRkfwTcP4_Vdq2YETG5TK9Q02v4cYmnLU03KBAJ0gcDha7oQ=s176-c-k-c0x00ffffff-no-rj',
    groups: ['English 2nd Gen', 'Hololive'],
    twitter: 'ceresfauna',
    aliases: ['fauna'],
  },
  {
    name: 'Laplus Darkness',
    ytId: 'UCENwRMx5Yh42zWpzURebzTw',
    chName: 'Laplus ch. ラプラス・ダークネス - holoX -',
    picture: 'dont put anything here',
    groups: ['6th Generation', 'Hololive'],
    twitter: 'LaplusDarknesss',
    aliases: ['Laplus'],
  },

  {
    name: 'Takane Lui',
    ytId: 'UCs9_O1tRPMQTHQ-N_L6FU2g',
    chName: 'Lui ch. 鷹嶺ルイ - holoX -',
    picture: 'dont put anything here',
    groups: ['6th Generation', 'Hololive'],
    twitter: 'takanelui',
    aliases: ['Lui'],
  },

  {
    name: 'Hakui Koyori',
    ytId: 'UC6eWCld0KwmyHFbAqK3V-Rw',
    chName: 'Koyori ch. 博衣こより - holoX -',
    picture: 'dont put anything here',
    groups: ['6th Generation', 'Hololive'],
    twitter: 'hakuikoyori',
    aliases: ['Koyori'],
  },

  {
    name: 'Sakamata Chloe',
    ytId: 'UCIBY1ollUsauvVi4hW4cumw',
    chName: 'Chloe ch. 沙花叉クロヱ - holoX -',
    picture: 'dont put anything here',
    groups: ['6th Generation', 'Hololive'],
    twitter: 'sakamatachloe',
    aliases: ['Chloe'],
  },
  {
    name: 'Kazama Iroha',
    ytId: 'UC_vMYWcDjmfdpH6r4TTn1MQ',
    chName: 'Iroha ch. 風真いろは - holoX -',
    picture: 'dont put anything here',
    groups: ['6th Generation', 'Hololive'],
    twitter: 'kazamairohach',
    aliases: ['Iroha'],
  },
  // id3
  {
    name: 'Vestia Zeta',
    ytId: 'UCTvHWSfBZgtxE4sILOaurIQ',
    chName: 'Vestia Zeta Ch. hololive-ID',
    picture: 'dont put anything here',
    groups: ['Indonesia 3rd Gen', 'Hololive'],
    twitter: 'vestiazeta',
    aliases: ['Zeta'],
  },
  {
    name: 'Kobo Kanaeru',
    ytId: 'UCjLEmnpCNeisMxy134KPwWw',
    chName: 'Kobo Kanaeru Ch. hololive-ID',
    picture: 'dont put anything here',
    groups: ['Indonesia 3rd Gen', 'Hololive'],
    twitter: 'kobokanaeru',
    aliases: ['kobo'],
  },
  {
    name: 'Kaela Kovalskia',
    ytId: 'UCZLZ8Jjx_RN2CXloOmgTHVg',
    chName: 'Kaela Kovalskia Ch. hololive-ID',
    picture: 'dont put anything here',
    groups: ['Indonesia 3rd Gen', 'Hololive'],
    twitter: 'kaelakovalskia',
    aliases: ['kaela'],
  },
  // tempus
  {
    name: 'Regis Altare',
    ytId: 'UCyxtGMdWlURZ30WSnEjDOQw',
    chName: 'Regis Altare Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Tempus', 'Hololive'],
    twitter: 'regisaltare',
    aliases: ['Regis'],
  },
  {
    name: 'Magni Dezmond',
    ytId: 'UC7MMNHR-kf9EN1rXiesMTMw',
    chName: 'Magni Dezmond Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Tempus', 'Hololive'],
    twitter: 'magnidezmond',
    aliases: ['Magni'],
  },
  {
    name: 'Axel Syrios',
    ytId: 'UC2hx0xVkMoHGWijwr_lA01w',
    chName: 'Axel Syrios Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Tempus', 'Hololive'],
    twitter: 'axelsyrios',
    aliases: ['Axel'],
  },
  {
    name: 'Noir Vesper',
    ytId: 'UCDRWSO281bIHYVi-OV3iFYA',
    chName: 'Noir Vesper Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Tempus', 'Hololive'],
    twitter: 'noirvesper_en',
    aliases: ['Noir'],
  },
  // uproar
  {
    name: 'Yatogami Fuma',
    ytId: 'UCc88OV45ICgHbn3ZqLLb52w',
    chName: 'Fuma Ch. 夜十神封魔 - UPROAR!! -',
    picture: 'dont put anything here',
    groups: ['Uproar', 'Hololive'],
    twitter: 'yatogamifuma',
    aliases: ['fuma'],
  },
  {
    name: 'Utsugi Uyu',
    ytId: 'UCgRqGV1gBf2Esxh0Tz1vxzw',
    chName: 'Uyu Ch. 羽継烏有 - UPROAR!! -',
    picture: 'dont put anything here',
    groups: ['Uproar', 'Hololive'],
    twitter: 'utsugiuyu',
    aliases: ['uyu'],
  },
  {
    name: 'Hizaki Gamma',
    ytId: 'UCkT1u65YS49ca_LsFwcTakw',
    chName: 'Gamma Ch. 緋崎ガンマ - UPROAR!! -',
    picture: 'dont put anything here',
    groups: ['Uproar', 'Hololive'],
    twitter: 'hizakigamma',
    aliases: ['gamma'],
  },
  {
    name: 'Minase Rio',
    ytId: 'UCdfMHxjcCc2HSd9qFvfJgjg',
    chName: 'Rio Ch. 水無世燐央 - UPROAR!! -',
    picture: 'dont put anything here',
    groups: ['Uproar', 'Hololive'],
    twitter: 'minaserioch',
    aliases: ['rio'],
  },
  // TEMPUS 2
  {
    name: 'Josuiji Shinri',
    ytId: 'UCMqGG8BRAiI1lJfKOpETM_w',
    chName: 'Josuiji Shinri Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Tempus', 'Hololive'],
    twitter: 'josuijishinri',
    aliases: ['Josuiji'],
  },
  {
    name: 'Banzoin Hakka',
    ytId: 'UC7gxU6NXjKF1LrgOddPzgTw',
    chName: 'Banzoin Hakka Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Tempus', 'Hololive'],
    twitter: 'banzoinhakka',
    aliases: ['Banzoin'],
  },
  {
    name: 'Machina X Flayon',
    ytId: 'UC060r4zABV18vcahAWR1n7w',
    chName: 'Machina X Flayon Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Tempus', 'Hololive'],
    twitter: 'machinaxflayon',
    aliases: ['Machina', 'Flayon', 'Flay'],
  },
  {
    name: 'Gavis Bettel',
    ytId: 'UCHP4f7G2dWD4qib7BMatGAw',
    chName: 'Gavis Bettel Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Tempus', 'Hololive'],
    twitter: 'gavisbettel',
    aliases: ['Gavis'],
  },
  {
    name: 'FUWAMOCO',
    ytId: 'UCt9H_RpQzhxzlyBxFqrdHqA',
    chName: 'FUWAMOCO Ch. hololive-EN',
    picture: 'dont put anything here',
    groups: ['English 3rd Gen', 'Hololive'],
    twitter: 'fuwamoco_en',
    aliases: ['FUWAMOCO', 'Fuwa', 'Fuwawa', 'Moco', 'Mococo'],
  },
  {
    name: 'Shiori Novella',
    ytId: 'UCgnfPPb9JI3e9A4cXHnWbyg',
    chName: 'Shiori Novella Ch. hololive-EN',
    picture: 'dont put anything here',
    groups: ['English 3rd Gen', 'Hololive'],
    twitter: 'shiorinovella',
    aliases: ['Shiori', 'Shio', 'Novella'],
  },
  {
    name: 'Koseki Bijou',
    ytId: 'UC9p_lqQ0FEDz327Vgf5JwqA',
    chName: 'Koseki Bijou Ch. hololive-EN',
    picture: 'dont put anything here',
    groups: ['English 3rd Gen', 'Hololive'],
    twitter: 'kosekibijou',
    aliases: ['Bijou', 'Koseki'],
  },
  {
    name: 'Nerissa Ravencroft',
    ytId: 'UC_sFNM0z0MWm9A6WlKPuMMg',
    chName: 'Nerissa Ravencroft Ch. hololive-EN',
    picture: 'dont put anything here',
    groups: ['English 3rd Gen', 'Hololive'],
    twitter: 'nerissa_en',
    aliases: ['Nerissa', 'Ravencroft'],
  },
  // ReGLOSS
  {
    name: 'Hiodoshi Ao',
    ytId: 'UCMGfV7TVTmHhEErVJg1oHBQ',
    chName: 'Ao Ch. 火威青 ‐ ReGLOSS',
    picture: 'dont put anything here',
    groups: ['ReGLOSS', 'Hololive'],
    twitter: 'hiodoshiao',
    aliases: ['Hiodoshi', 'Ao'],
  },
  {
    name: 'Otonose Kanade',
    ytId: 'UCWQtYtq9EOB4-I5P-3fh8lA',
    chName: 'Kanade Ch. 音乃瀬奏 ‐ ReGLOSS',
    picture: 'dont put anything here',
    groups: ['ReGLOSS', 'Hololive'],
    twitter: 'otonosekanade',
    aliases: ['Otonose', 'Kanade'],
  },
  {
    name: 'Ichijou Ririka',
    ytId: 'UCtyWhCj3AqKh2dXctLkDtng',
    chName: 'Ririka Ch. 一条莉々華 ‐ ReGLOSS',
    picture: 'dont put anything here',
    groups: ['ReGLOSS', 'Hololive'],
    twitter: 'ichijouririka',
    aliases: ['Ichijou', 'Ririka'],
  },
  {
    name: 'Juufuutei Raden',
    ytId: 'UCdXAk5MpyLD8594lm_OvtGQ',
    chName: 'Raden Ch. 儒烏風亭らでん ‐ ReGLOSS',
    picture: 'dont put anything here',
    groups: ['ReGLOSS', 'Hololive'],
    twitter: 'juufuuteiraden',
    aliases: ['Juufuutei', 'Raden'],
  },
  {
    name: 'Todoroki Hajime',
    ytId: 'UC1iA6_NT4mtAcIII6ygrvCw',
    chName: 'Hajime Ch. 轟はじめ ‐ ReGLOSS',
    picture: 'dont put anything here',
    groups: ['ReGLOSS', 'Hololive'],
    twitter: 'todoroki_hajime',
    aliases: ['Todoroki', 'Hajime'],
  },
  {
    name: 'Jurard T Rexford',
    ytId: 'UCTVSOgYuSWmNAt-lnJPkEEw',
    chName: 'Jurard T Rexford Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Armis', 'Hololive'],
    twitter: 'jurardtrexford',
    aliases: ['Jurard', 'Rexford'],
  },
  {
    name: 'Goldbullet',
    ytId: 'UCJv02SHZgav7Mv3V0kBOR8Q',
    chName: 'Goldbullet Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Armis', 'Hololive'],
    twitter: 'goldbullet_en',
    aliases: ['goldbullet'],
  },
  {
    name: 'Octavio',
    ytId: 'UCLk1hcmxg8rJ3Nm1_GvxTRA',
    chName: 'Octavio Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Armis', 'Hololive'],
    twitter: 'octavio_holo',
    aliases: ['octavio'],
  },
  {
    name: 'Crimzon Ruze',
    ytId: 'UCajbFh6e_R8QZdHAMbbi4rQ',
    chName: 'Crimzon Ruze Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Armis', 'Hololive'],
    twitter: 'crimzonruze',
    aliases: ['Crimzon', 'Ruze'],
  }
] as const
