export const hololive_jp = [
  {
    name: 'AZKi',
    ytId: 'UC0TXe_LYZ4scaW2XMyi5_kw',
    chName: 'AZKi Channel',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnh85tQLdg3chip7aFBjFZyORHi40WPjcFRWaQq8Wg=s800-c-k-c0x00ffffff-no-rj',
    groups: ['0th Generation', 'Hololive'],
    twitter: 'AZKi_VDiVA',
    aliases: ['azki'],
  },
  {
    name: 'Akai Haato',
    ytId: 'UC1CfXB_kRs3C-zaeTG3oGyg',
    chName: 'HAACHAMA Ch 赤井はあと',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwniwFyaWXOPJEGqA3afhSvRsiPDb0sYt8TlCMMWIig=s800-c-k-c0x00ffffff-no-rj',
    groups: ['1st Generation', 'Hololive'],
    twitter: 'akaihaato',
    aliases: ['haato', 'haachama', 'はあちゃま', 'はあと'],
  },
  {
    name: 'Darkweb Haachama',
    ytId: 'UCHj_mh57PVMXhAUDphUQDFA',
    chName: 'HAACHAMA DARKWEB CH',
    picture: 'n/a',
    groups: ['1st Generation', 'Hololive'],
    twitter: 'akaihaato',
    aliases: [],
  },
  {
    name: 'Usada Pekora',
    ytId: 'UC1DCedRgGHBdm81E1llLhOQ',
    chName: 'Pekora Ch. 兎田ぺこら',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnjvkyPGzOmEXZ34mEFPlwMKTbCDl1ZkQ_HkxY-O5Q=s800-c-k-c0x00ffffff-no-rj',
    groups: ['3rd Generation', 'Hololive'],
    twitter: 'usadapekora',
    aliases: ['peko', 'ペコ', 'ぺこ'],
  },
  {
    name: 'Minato Aqua',
    ytId: 'UC1opHUrw8rvnsadT-iGp7Cg',
    chName: 'Aqua Ch. 湊あくあ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwngPGs1t6iJAT6hLWj7cBQcvJg2y_L9mzpy3lpxgqw=s800-c-k-c0x00ffffff-no-rj',
    groups: ['2nd Generation', 'Hololive'],
    twitter: 'minatoaqua',
    aliases: ['aqua', 'baqua', 'akutan', 'あくあ', 'あくたん'],
  },
  {
    name: 'Yuzuki Choco',
    ytId: 'UC1suqwovbL1kzsoaZgFZLKg',
    chName: 'Choco Ch. 癒月ちょこ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnjONtr2IgqiXteDRhXt_yOiWlgPLicWOESGvKzZPQ=s800-c-k-c0x00ffffff-no-rj',
    groups: ['2nd Generation', 'Hololive'],
    twitter: 'yuzukichococh',
    aliases: ['choco', 'chocosen', 'ちょこ'],
  },
  {
    name: 'Tokoyami Towa',
    ytId: 'UC1uv2Oq6kNxgATlCiez59hw',
    chName: 'Towa Ch. 常闇トワ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnjPaiimZva5GECAyNDn0qraqPm62LlH-0oN21I5=s800-c-k-c0x00ffffff-no-rj',
    groups: ['4th Generation', 'Hololive'],
    twitter: 'tokoyamitowa',
    aliases: ['towa', 'トワ'],
  },
  {
    name: 'Hoshimachi Suisei',
    ytId: 'UC5CwaMl1eIgY8h02uZw7u8A',
    chName: 'Suisei Channel',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnjdAl5rn3IjWzl55_0-skvKced7znPZRuPC5xLB=s800-c-k-c0x00ffffff-no-rj',
    groups: ['0th Generation', 'Hololive'],
    twitter: 'suisei_hosimati',
    aliases: ['suisei', 'suichan', 'sui-chan', 'すいせい', 'すいちゃん'],
  },
  {
    name: 'Nakiri Ayame',
    ytId: 'UC7fk0CB07ly8oSl0aqKkqFg',
    chName: 'Nakiri Ayame Ch. 百鬼あやめ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnh66ZORNcVma4Pn-Qic23kU3Kl4ZkHM3asCWjDh=s800-c-k-c0x00ffffff-no-rj',
    groups: ['2nd Generation', 'Hololive'],
    twitter: 'nakiriayame',
    aliases: ['ayame', 'nakiri', 'あやめ'],
  },
  {
    name: 'Himemori Luna',
    ytId: 'UCa9Y57gfeY0Zro_noHRVrnw',
    chName: 'Luna Ch. 姫森ルーナ',
    picture:
      'https://yt3.ggpht.com/eUvyn2QlPppt7z5wew0upiGt2-o7c7rLKBlWynTrSdacjvtZYxZ7Sp6MuYumQJ-zSwzj6a6BDA=s800-c-k-c0x00ffffff-no-rj',
    groups: ['4th Generation', 'Hololive'],
    twitter: 'himemoriluna',
    aliases: ['ルーナ', 'luna'],
  },
  {
    name: 'Momosuzu Nene',
    ytId: 'UCAWSyEs_Io8MtpY3m-zqILA',
    chName: 'Nene Ch.桃鈴ねね',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnilXc5WPsj69fn_xew6see04Cmj3x1vIkW62boi=s800-c-k-c0x00ffffff-no-rj',
    groups: ['5th Generation', 'Hololive'],
    twitter: 'momosuzunene',
    aliases: ['nene', 'ねね', 'nenechi'],
  },
  {
    name: 'Houshou Marine',
    ytId: 'UCCzUftO8KOVkV4wQG1vkUvg',
    chName: 'Marine Ch. 宝鐘マリン',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnjPuFWs42Vx2yIhK7z1w4L-e1GIpHn_5R1uknbS=s800-c-k-c0x00ffffff-no-rj',
    groups: ['3rd Generation', 'Hololive'],
    twitter: 'houshoumarine',
    aliases: ['marine', '船長', 'senchou', 'sentyo', 'mari-tan', 'maripi'],
  },
  {
    name: 'Yozora Mel',
    ytId: 'UCD8HOxPs4Xvsm8H0ZxXGiBw',
    chName: 'Mel Channel 夜空メルチャンネル',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnj5J44v4_Ua9qGrh_n8IR0Dp-r2yj0Nl0mv4lkR=s800-c-k-c0x00ffffff-no-rj',
    groups: ['1st Generation', 'Hololive'],
    twitter: 'yozoramel',
    aliases: ['mel', 'メル'],
  },
  {
    name: 'Shirakami Fubuki',
    ytId: 'UCdn5BQ06XqgXoAxIhbqw5Rg',
    chName: 'フブキCh。白上フブキ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwniEQsukDZoC-l8zchhRzpraxcH7Fyq9amrj2980Aw=s800-c-k-c0x00ffffff-no-rj',
    groups: ['1st Generation', 'Hololive'],
    twitter: 'shirakamifubuki',
    aliases: ['fubuki', 'fbk', 'フブキ'],
  },
  {
    name: 'Roboco-san',
    ytId: 'UCDqI2jOz0weumE8s7paEk6g',
    chName: 'Roboco Ch. - ロボ子',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnhx_THxk2jgqmEGA-cliO482QCna3lnmCBFvCdtBg=s800-c-k-c0x00ffffff-no-rj',
    groups: ['0th Generation', 'Hololive'],
    twitter: 'robocosan',
    aliases: ['roboco', 'ロボ子'],
  },
  {
    name: 'Shirogane Noel',
    ytId: 'UCdyqAaZDKHXg4Ahi7VENThQ',
    chName: 'Noel Ch. 白銀ノエル',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnijLF2X1YBVQo3rClt7ub29cYM7OzpmRmliaGbw=s800-c-k-c0x00ffffff-no-rj',
    groups: ['3rd Generation', 'Hololive'],
    twitter: 'shiroganenoel',
    aliases: ['noel', 'ノエル', 'danchou', '団長'],
  },
  {
    name: 'Yukihana Lamy',
    ytId: 'UCFKOVgVbGmX65RxO3EtH3iw',
    chName: 'Lamy Ch. 雪花ラミィ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwng8eQJdCX3r4RgCmRGwigXkDp9a2JJSPq-dZcMF=s800-c-k-c0x00ffffff-no-rj',
    groups: ['5th Generation', 'Hololive'],
    twitter: 'yukihanalamy',
    aliases: ['lamy', 'らみ', 'ラミィ'],
  },
  {
    name: 'Aki Rosenthal',
    ytId: 'UCFTLzh12_nrtzqBPsTCqenA',
    chName: 'アキロゼCh。Vtuber/ホロライブ所属',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnhPGqWt_E_8rBXpKUTgHCuyTq0Zz7TXlkRtiIww=s800-c-k-c0x00ffffff-no-rj',
    groups: ['1st Generation', 'Hololive'],
    twitter: 'akirosenthal',
    aliases: ['aki', 'アキ'],
  },
  {
    name: 'Inugami Korone',
    ytId: 'UChAnqc_AY5_I3Px5dig3X1Q',
    chName: 'Korone Ch. 戌神ころね',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnj7QwmJ9YhyKY-9SkOKhKIzTKDMJp0HX2vAdQUVdw=s800-c-k-c0x00ffffff-no-rj',
    groups: ['GAMERS', 'Hololive'],
    twitter: 'inugamikorone',
    aliases: ['korone', 'korosan', 'ころね', 'ころさん'],
  },
  {
    name: 'Sakura Miko',
    ytId: 'UC-hM6YJuNYVAmUWxeIr9FeA',
    chName: 'Miko Ch. さくらみこ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwniR0ijvAPNICEVzF8Pz0kSkuhBLKXd31oc5yO-0AQ=s800-c-k-c0x00ffffff-no-rj',
    groups: ['0th Generation', 'Hololive'],
    twitter: 'sakuramiko35',
    aliases: ['miko', 'mikoti', 'mikocchi', 'みこ', 'みこっち'],
  },
  {
    name: 'Omaru Polka',
    ytId: 'UCK9V2B22uJYu3N7eR_BT9QA',
    chName: 'Polka Ch. 尾丸ポルカ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnh-sak3t15svmMDNF8w_uxnNEChOL7C1DKAO-Ht=s800-c-k-c0x00ffffff-no-rj',
    groups: ['5th Generation', 'Hololive'],
    twitter: 'omarupolka',
    aliases: ['polka', 'omaru', 'ポル', 'おまる', 'omarun'],
  },
  {
    name: 'Ookami Mio',
    ytId: 'UCp-5t9SrOQwXMU7iIjQfARg',
    chName: 'Mio Channel 大神ミオ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwng30Wmfu39r1PLrF05pvAafn2a2Ex90ok2C6CTBmg=s800-c-k-c0x00ffffff-no-rj',
    groups: ['GAMERS', 'Hololive'],
    twitter: 'ookamimio',
    aliases: ['mio', 'みお'],
  },
  {
    name: 'Tokino Sora',
    ytId: 'UCp6993wxpyDPHUpavwDFqgg',
    chName: 'SoraCh. ときのそらチャンネル',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwngZmr_qbKhGIvHaHwLRmKhKxdeFfM7ZbK316vFNSw=s800-c-k-c0x00ffffff-no-rj',
    groups: ['0th Generation', 'Hololive'],
    twitter: 'tokino_sora',
    aliases: ['sora', 'そら'],
  },
  {
    name: 'Natsuiro Matsuri',
    ytId: 'UCQ0UDLQCjY0rmuxCDE38FGg',
    chName: 'Matsuri Channel 夏色まつり',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwni8cjtyc08E7rocvO9_gR1b5BhO1O6O1VreDxMW=s800-c-k-c0x00ffffff-no-rj',
    groups: ['1st Generation', 'Hololive'],
    twitter: 'natsuiromatsuri',
    aliases: ['matsuri', 'まつり'],
  },
  {
    name: 'Tsunomaki Watame',
    ytId: 'UCqm3BQLlJfvkTsX_hvm0UmA',
    chName: 'Watame Ch. 角巻わため',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnitWcmmZK60TDG8y5aUeQfZlmH9YlBNJ4D1ZSFI=s800-c-k-c0x00ffffff-no-rj',
    groups: ['4th Generation', 'Hololive'],
    twitter: 'tsunomakiwatame',
    aliases: ['watame', 'わため'],
  },
  {
    name: 'Shishiro Botan',
    ytId: 'UCUKD-uaobj9jiqB-VXt71mA',
    chName: 'Botan Ch.獅白ぼたん',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwngRC-JqguPnj9ljVH3UulyfdlyQzLYzLeSrhvD6=s800-c-k-c0x00ffffff-no-rj',
    groups: ['5th Generation', 'Hololive'],
    twitter: 'shishirobotan',
    aliases: ['botan', 'ぼたん', 'shishiron', 'bossan'],
  },
  {
    name: 'Nekomata Okayu',
    ytId: 'UCvaTdHTWBGv3MKj3KVqJVCw',
    chName: 'Okayu Ch. 猫又おかゆ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnjXQ3Gt3t3SdUMZHBhhEb_c1jqThHfDaVNJF_LJ=s800-c-k-c0x00ffffff-no-rj',
    groups: ['GAMERS', 'Hololive'],
    twitter: 'nekomataokayu',
    aliases: ['okayu', 'おかゆ'],
  },
  {
    name: 'Shiranui Flare',
    ytId: 'UCvInZx9h3jC2JzsIzoOebWg',
    chName: 'Flare Ch. 不知火フレア',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwngtkUgGkgWTz57Er3GSzuMUR07HISM_yDhKQFnR_A=s800-c-k-c0x00ffffff-no-rj',
    groups: ['3rd Generation', 'Hololive'],
    twitter: 'shiranuiflare',
    aliases: ['flare', 'フレア'],
  },
  {
    name: 'Oozora Subaru',
    ytId: 'UCvzGlP9oQwU--Y0r9id_jnA',
    chName: 'Subaru Ch. 大空スバル',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwniCgko15I_x5bYWm0G2vnf5hZqD5hLOtLEDw0Na=s800-c-k-c0x00ffffff-no-rj',
    groups: ['2nd Generation', 'Hololive'],
    twitter: 'oozorasubaru',
    aliases: ['subaru', 'shuba', 'スバル'],
  },
  {
    name: 'Murasaki Shion',
    ytId: 'UCXTpFs_3PqI41qX2d9tL2Rw',
    chName: 'Shion Ch. 紫咲シオン',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwni5CHNTkw8RlOj-78oqDbWS6sEdH4VQR_c06B6s6Q=s800-c-k-c0x00ffffff-no-rj',
    groups: ['2nd Generation', 'Hololive'],
    twitter: 'murasakishionch',
    aliases: ['shion', 'シオン', 'kusogaki', 'クソガキ'],
  },
  {
    name: 'Amane Kanata',
    ytId: 'UCZlDXzGoo7d44bwdNObFacg',
    chName: 'Kanata Ch. 天音かなた',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwniXUgLD1FepLsMoqO7HnhlgwbxGmPeqKWGv1JsO=s800-c-k-c0x00ffffff-no-rj',
    groups: ['4th Generation', 'Hololive'],
    twitter: 'amanekanatach',
    aliases: ['kanata', 'かなた', 'pp tenshi', 'かなごり', 'kanataso', 'kanatan', 'kanakana', 'kanata-senpai', 'kanata-san'],
  },
  {
    name: 'Laplus Darkness',
    ytId: 'UCENwRMx5Yh42zWpzURebzTw',
    chName: 'Laplus ch. ラプラス・ダークネス - holoX -',
    picture: 'dont put anything here',
    groups: ['6th Generation', 'Hololive'],
    twitter: 'LaplusDarknesss',
    aliases: ['Laplus'],
  },

  {
    name: 'Takane Lui',
    ytId: 'UCs9_O1tRPMQTHQ-N_L6FU2g',
    chName: 'Lui ch. 鷹嶺ルイ - holoX -',
    picture: 'dont put anything here',
    groups: ['6th Generation', 'Hololive'],
    twitter: 'takanelui',
    aliases: ['Lui'],
  },

  {
    name: 'Hakui Koyori',
    ytId: 'UC6eWCld0KwmyHFbAqK3V-Rw',
    chName: 'Koyori ch. 博衣こより - holoX -',
    picture: 'dont put anything here',
    groups: ['6th Generation', 'Hololive'],
    twitter: 'hakuikoyori',
    aliases: ['Koyori'],
  },

  {
    name: 'Sakamata Chloe',
    ytId: 'UCIBY1ollUsauvVi4hW4cumw',
    chName: 'Chloe ch. 沙花叉クロヱ - holoX -',
    picture: 'dont put anything here',
    groups: ['6th Generation', 'Hololive'],
    twitter: 'sakamatachloe',
    aliases: ['Chloe'],
  },
  {
    name: 'Kazama Iroha',
    ytId: 'UC_vMYWcDjmfdpH6r4TTn1MQ',
    chName: 'Iroha ch. 風真いろは - holoX -',
    picture: 'dont put anything here',
    groups: ['6th Generation', 'Hololive'],
    twitter: 'kazamairohach',
    aliases: ['Iroha'],
  },
  {
    name: 'Hiodoshi Ao',
    ytId: 'UCMGfV7TVTmHhEErVJg1oHBQ',
    chName: 'Ao Ch. 火威青 ‐ ReGLOSS',
    picture: 'dont put anything here',
    groups: ['ReGLOSS', 'Hololive'],
    twitter: 'hiodoshiao',
    aliases: ['Hiodoshi', 'Ao'],
  },
  {
    name: 'Otonose Kanade',
    ytId: 'UCWQtYtq9EOB4-I5P-3fh8lA',
    chName: 'Kanade Ch. 音乃瀬奏 ‐ ReGLOSS',
    picture: 'dont put anything here',
    groups: ['ReGLOSS', 'Hololive'],
    twitter: 'otonosekanade',
    aliases: ['Otonose', 'Kanade'],
  },
  {
    name: 'Ichijou Ririka',
    ytId: 'UCtyWhCj3AqKh2dXctLkDtng',
    chName: 'Ririka Ch. 一条莉々華 ‐ ReGLOSS',
    picture: 'dont put anything here',
    groups: ['ReGLOSS', 'Hololive'],
    twitter: 'ichijouririka',
    aliases: ['Ichijou', 'Ririka'],
  },
  {
    name: 'Juufuutei Raden',
    ytId: 'UCdXAk5MpyLD8594lm_OvtGQ',
    chName: 'Raden Ch. 儒烏風亭らでん ‐ ReGLOSS',
    picture: 'dont put anything here',
    groups: ['ReGLOSS', 'Hololive'],
    twitter: 'juufuuteiraden',
    aliases: ['Juufuutei', 'Raden'],
  },
  {
    name: 'Todoroki Hajime',
    ytId: 'UC1iA6_NT4mtAcIII6ygrvCw',
    chName: 'Hajime Ch. 轟はじめ ‐ ReGLOSS',
    picture: 'dont put anything here',
    groups: ['ReGLOSS', 'Hololive'],
    twitter: 'todoroki_hajime',
    aliases: ['Todoroki', 'Hajime'],
  },
] as const
