export const holostars = [
  {
    name: 'Hanasaki Miyabi',
    ytId: 'UC6t3-_N8A6ME1JShZHHqOMw',
    chName: 'Miyabi Ch. 花咲みやび',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnj2P4FOShzQPX2-1rLfO_3Vbo7IyKQdK1PiF65w=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Holostars 1st Gen', 'Hololive'],
    twitter: 'miyabihanasaki',
    aliases: ['miyabi', 'みやび'],
  },
  {
    name: 'Rikkaroid',
    ytId: 'UC9mf_ZVpouoILRY9NUIaK-w',
    chName: 'Rikka ch.律可',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnghUH22DLP22EHC3PZP7xXzJFd7qS_scK95WhaQ=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Holostars 1st Gen', 'Hololive'],
    twitter: 'rikkaroid',
    aliases: ['rikka', 'rikka', 'りっか', '律可'],
  },
  {
    name: 'Yukoku Roberu',
    ytId: 'UCANDOlYTJT7N5jlRC3zfzVA',
    chName: 'Roberu Ch. 夕刻ロベル',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwngPbWJ4YAEgQiAMkgMwLh_0AV_I7SbRhW-s4h_p=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Holostars 2nd Generation', 'Hololive'],
    twitter: 'yukokuroberu',
    aliases: ['winning son', 'roberu', 'ロベル'],
  },
  {
    name: 'Kishido Temma',
    ytId: 'UCGNI4MENvnsymYjKiZwv9eg',
    chName: 'Temma Ch. 岸堂天真',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnjek7CeN83n90k6OaFaezz0vdgXe5RYaxl_nPaX=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Holostars 2nd Generation', 'Hololive'],
    twitter: 'kishidotemma',
    aliases: ['temma', '天真', 'てんま'],
  },
  {
    name: 'Kageyama Shien',
    ytId: 'UChSvpZYRPh0FvG4SJGSga3g',
    chName: 'Shien Ch.影山シエン',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnjvoMWzRyWOvk4jbneB4C0O97oCXrLUDV9twwsN=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Holostars 3rd Gen', 'Hololive'],
    twitter: 'kageyamashien',
    aliases: ['shien', 'シエン'],
  },
  {
    name: 'Arurandeisu',
    ytId: 'UCKeAhJvy8zgXWbh9duVjIaQ',
    chName: 'Aruran Ch. アルランディス',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnjIqTphTjcWJLTftb3ppGk71CVwCYaH2M5KkmZOAQ=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Holostars 1st Gen', 'Hololive'],
    twitter: 'arurandeisu',
    aliases: ['aruran'],
  },
  {
    name: 'Astel Leda',
    ytId: 'UCNVEsYbiZjH5QLmGeSgTSzg',
    chName: 'astel ch.アステル',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwngMQoYWdT6G-GUOnGKmzbFoLBTdsjb2G5rS8ZbH=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Holostars 2nd Generation', 'Hololive'],
    twitter: 'astelleda',
    aliases: ['astel', 'アステル'],
  },
  {
    name: 'Aragami Oga',
    ytId: 'UCwL7dgTxKo8Y4RFIKWaf8gA',
    chName: 'Oga Ch.荒咬オウガ',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnie3tYJpu_RdoJWWMjNkj-mUS7-F4QtE1nNY8N_=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Holostars 3rd Gen', 'Hololive'],
    twitter: 'aragamioga',
    aliases: ['oga'],
  },
  {
    name: 'Kanade Izuru',
    ytId: 'UCZgOv3YDEs-ZnZWDYVwJdmA',
    chName: 'Izuru Ch. 奏手イヅル',
    picture:
      'https://yt3.ggpht.com/ytc/AAUvwnhNA5NPSYpFiMba_lmeNqYZJ4bVtZKf-5g5YlxGcA=s800-c-k-c0x00ffffff-no-rj',
    groups: ['Holostars 1st Gen', 'Hololive'],
    twitter: 'kanadeizuru',
    aliases: ['izuru'],
  },
  {
    name: 'Regis Altare',
    ytId: 'UCyxtGMdWlURZ30WSnEjDOQw',
    chName: 'Regis Altare Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Tempus', 'Hololive'],
    twitter: 'regisaltare',
    aliases: ['Regis'],
  },
  {
    name: 'Magni Dezmond',
    ytId: 'UC7MMNHR-kf9EN1rXiesMTMw',
    chName: 'Magni Dezmond Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Tempus', 'Hololive'],
    twitter: 'magnidezmond',
    aliases: ['Magni'],
  },
  {
    name: 'Axel Syrios',
    ytId: 'UC2hx0xVkMoHGWijwr_lA01w',
    chName: 'Axel Syrios Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Tempus', 'Hololive'],
    twitter: 'axelsyrios',
    aliases: ['Axel'],
  },
  {
    name: 'Noir Vesper',
    ytId: 'UCDRWSO281bIHYVi-OV3iFYA',
    chName: 'Noir Vesper Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Tempus', 'Hololive'],
    twitter: 'noirvesper_en',
    aliases: ['Noir'],
  },
  {
    name: 'Yatogami Fuma',
    ytId: 'UCc88OV45ICgHbn3ZqLLb52w',
    chName: 'Fuma Ch. 夜十神封魔 - UPROAR!! -',
    picture: 'dont put anything here',
    groups: ['Uproar', 'Hololive'],
    twitter: 'yatogamifuma',
    aliases: ['fuma'],
  },
  {
    name: 'Utsugi Uyu',
    ytId: 'UCgRqGV1gBf2Esxh0Tz1vxzw',
    chName: 'Uyu Ch. 羽継烏有 - UPROAR!! -',
    picture: 'dont put anything here',
    groups: ['Uproar', 'Hololive'],
    twitter: 'utsugiuyu',
    aliases: ['uyu'],
  },
  {
    name: 'Hizaki Gamma',
    ytId: 'UCkT1u65YS49ca_LsFwcTakw',
    chName: 'Gamma Ch. 緋崎ガンマ - UPROAR!! -',
    picture: 'dont put anything here',
    groups: ['Uproar', 'Hololive'],
    twitter: 'hizakigamma',
    aliases: ['gamma'],
  },
  {
    name: 'Minase Rio',
    ytId: 'UCdfMHxjcCc2HSd9qFvfJgjg',
    chName: 'Rio Ch. 水無世燐央 - UPROAR!! -',
    picture: 'dont put anything here',
    groups: ['Uproar', 'Hololive'],
    twitter: 'minaserioch',
    aliases: ['rio'],
  },
  {
    name: 'Josuiji Shinri',
    ytId: 'UCMqGG8BRAiI1lJfKOpETM_w',
    chName: 'Josuiji Shinri Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Tempus', 'Hololive'],
    twitter: 'josuijishinri',
    aliases: ['Josuiji'],
  },
  {
    name: 'Banzoin Hakka',
    ytId: 'UC7gxU6NXjKF1LrgOddPzgTw',
    chName: 'Banzoin Hakka Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Tempus', 'Hololive'],
    twitter: 'banzoinhakka',
    aliases: ['Banzoin'],
  },
  {
    name: 'Machina X Flayon',
    ytId: 'UC060r4zABV18vcahAWR1n7w',
    chName: 'Machina X Flayon Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Tempus', 'Hololive'],
    twitter: 'machinaxflayon',
    aliases: ['Machina', 'Flayon', 'Flay'],
  },
  {
    name: 'Gavis Bettel',
    ytId: 'UCHP4f7G2dWD4qib7BMatGAw',
    chName: 'Gavis Bettel Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Tempus', 'Hololive'],
    twitter: 'gavisbettel',
    aliases: ['Gavis'],
  },
  {
    name: 'Jurard T Rexford',
    ytId: 'UCTVSOgYuSWmNAt-lnJPkEEw',
    chName: 'Jurard T Rexford Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Armis', 'Hololive'],
    twitter: 'jurardtrexford',
    aliases: ['Jurard', 'Rexford'],
  },
  {
    name: 'Goldbullet',
    ytId: 'UCJv02SHZgav7Mv3V0kBOR8Q',
    chName: 'Goldbullet Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Armis', 'Hololive'],
    twitter: 'goldbullet_en',
    aliases: ['goldbullet'],
  },
  {
    name: 'Octavio',
    ytId: 'UCLk1hcmxg8rJ3Nm1_GvxTRA',
    chName: 'Octavio Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Armis', 'Hololive'],
    twitter: 'octavio_holo',
    aliases: ['octavio'],
  },
  {
    name: 'Crimzon Ruze',
    ytId: 'UCajbFh6e_R8QZdHAMbbi4rQ',
    chName: 'Crimzon Ruze Ch. HOLOSTARS-EN',
    picture: 'dont put anything here',
    groups: ['Armis', 'Hololive'],
    twitter: 'crimzonruze',
    aliases: ['Crimzon', 'Ruze'],
  }
] as const